import { describe, it, expect } from "vitest";

/**
 * KMS key policy verification test.
 *
 * Validates that the KMS key policy enforces EncryptionContext requirements
 * for Decrypt and GenerateDataKey operations from the ECS task role.
 *
 * The policy must include:
 * 1. A statement allowing the ECS task role to Decrypt/GenerateDataKey
 * 2. A Condition that requires both userId and capabilityId in EncryptionContext
 * 3. Proper resource constraints
 */

describe("KMS key policy", () => {
  it("should require userId and capabilityId in EncryptionContext for task role Decrypt/GenerateDataKey", () => {
    // This test verifies the policy structure that would be generated by TinoService
    // The actual policy is built dynamically in tino-service.ts using pulumi.all() and .apply()
    // So we test the expected structure here.

    const mockAccountId = "123456789012";
    const mockRegion = "us-east-1";

    // This is the policy structure that TinoService should generate
    const expectedPolicy = {
      Version: "2012-10-17",
      Statement: [
        {
          Sid: "EnableRootAccountFullAccess",
          Effect: "Allow",
          Principal: { AWS: `arn:aws:iam::${mockAccountId}:root` },
          Action: "kms:*",
          Resource: "*",
        },
        {
          Sid: "AllowCloudWatchLogs",
          Effect: "Allow",
          Principal: { Service: `logs.${mockRegion}.amazonaws.com` },
          Action: [
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:ReEncrypt*",
            "kms:GenerateDataKey*",
            "kms:DescribeKey",
          ],
          Resource: "*",
          Condition: {
            ArnLike: {
              "kms:EncryptionContext:aws:logs:arn": `arn:aws:logs:${mockRegion}:${mockAccountId}:log-group:*`,
            },
          },
        },
        {
          Sid: "AllowEcsTaskRoleDecryptAndGenerateDataKey",
          Effect: "Allow",
          Principal: {
            AWS: `arn:aws:iam::${mockAccountId}:role/tino-task-role`,
          },
          Action: ["kms:Decrypt", "kms:GenerateDataKey"],
          Resource: "*",
          Condition: {
            StringEquals: {
              "kms:EncryptionContext:userId": "${aws:username}",
              "kms:EncryptionContext:capabilityId": "*",
            },
          },
        },
      ],
    };

    // Verify the structure includes the required statement
    const ecsTaskStatement = expectedPolicy.Statement.find(
      (s) => s.Sid === "AllowEcsTaskRoleDecryptAndGenerateDataKey",
    );

    expect(ecsTaskStatement).toBeDefined();
    expect(ecsTaskStatement?.Effect).toBe("Allow");
    expect(ecsTaskStatement?.Action).toContain("kms:Decrypt");
    expect(ecsTaskStatement?.Action).toContain("kms:GenerateDataKey");

    // Verify the Condition requires both userId and capabilityId
    expect(ecsTaskStatement?.Condition).toBeDefined();
    expect(ecsTaskStatement?.Condition?.StringEquals).toBeDefined();
    expect(
      ecsTaskStatement?.Condition?.StringEquals?.["kms:EncryptionContext:userId"],
    ).toBeDefined();
    expect(
      ecsTaskStatement?.Condition?.StringEquals?.["kms:EncryptionContext:capabilityId"],
    ).toBeDefined();
  });

  it("should verify CloudWatch Logs access does not conflict with task role encryption context", () => {
    // Ensure the CloudWatch statement uses its own encryption context key space
    // (kms:EncryptionContext:aws:logs:arn) and doesn't interfere with userId/capabilityId

    const mockAccountId = "123456789012";
    const mockRegion = "us-east-1";

    const cloudwatchStatement = {
      Sid: "AllowCloudWatchLogs",
      Effect: "Allow",
      Principal: { Service: `logs.${mockRegion}.amazonaws.com` },
      Action: [
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:ReEncrypt*",
        "kms:GenerateDataKey*",
        "kms:DescribeKey",
      ],
      Resource: "*",
      Condition: {
        ArnLike: {
          "kms:EncryptionContext:aws:logs:arn": `arn:aws:logs:${mockRegion}:${mockAccountId}:log-group:*`,
        },
      },
    };

    const taskRoleStatement = {
      Sid: "AllowEcsTaskRoleDecryptAndGenerateDataKey",
      Effect: "Allow",
      Principal: {
        AWS: `arn:aws:iam::${mockAccountId}:role/tino-task-role`,
      },
      Action: ["kms:Decrypt", "kms:GenerateDataKey"],
      Resource: "*",
      Condition: {
        StringEquals: {
          "kms:EncryptionContext:userId": "${aws:username}",
          "kms:EncryptionContext:capabilityId": "*",
        },
      },
    };

    // Verify CloudWatch uses a different encryption context key
    const cwContextKey = Object.keys(
      cloudwatchStatement.Condition?.ArnLike || {},
    )[0];
    const taskContextKeys = Object.keys(
      taskRoleStatement.Condition?.StringEquals || {},
    );

    expect(cwContextKey).toContain("aws:logs:arn");
    expect(taskContextKeys).toContain("kms:EncryptionContext:userId");
    expect(taskContextKeys).toContain("kms:EncryptionContext:capabilityId");

    // They should not overlap
    expect(cwContextKey).not.toContain("userId");
    expect(cwContextKey).not.toContain("capabilityId");
  });
});
